### ISSUE TITLE
undefined.json

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/docker-pubchem#27]
originalData/coconut/full/coconut.2022-03-28.zip
originalData/coconut/full/uniqueNaturalProduct.undefined.bson

**Comment by RicardoSilvestr** [comment]
Not happening anymore as can be seen by telegram log:
```
08:17:56.025 - syncCoconut:Start parsing: /originalData/coconut/full/uniqueNaturalProduct.2022-04-06.bson

```
