### ISSUE TITLE
check if file size is identical before assuming the file is ok

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/docker-pubchem#29]
https://github.com/cheminfo/docker-pubchem/blob/ddf46a95c99f84a718f2d72820128c358eb8d27c/pubchem/src/plugins/coconut/sync/syncCoconut.js#L48-L53

**Comment by RicardoSilvestr** [comment]
we should add a function in getFileIfNew() to handle network lost, otherwise we will face the same problem described above

**Comment by lpatiny** [comment]
Indeed we should not keep a partially downloaded file. If there is any network loss we could maybe retry but anyway delete the file that was downloaded.

**Comment by lpatiny** [comment]
Seems to me it is general. If it fails to download or to decompress we delete the file. But this means that next time we should consider that the download succeeded (so we don't need to redownload) but the decompression fails (so we need to decompress).

**Comment by RicardoSilvestr** [comment]
This issue should be ok @lpatiny

**Comment by RicardoSilvestr** [comment]
solved
