### ISSUE TITLE
Add a flag when the importation is completed for sure

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/docker-pubchem#30]
Currently we try to reimport the last file even if we are 'sure' that it was completed.

We could add a flag in the admin collection when the importation is completed and skip if trying to reimport.

**Comment by RicardoSilvestr** [comment]
ps. I forgot to add the reference to the last commit, please use the url bellow:
https://github.com/cheminfo/docker-pubchem/commit/fb829531d44d3cc23b324f67bec86d4899adcf1a
