### ISSUE TITLE
getNoStereoID( ) is too slow 

### ISSUE THREAD

**Issue by RicardoSilvestr** [cheminfo/docker-pubchem#65]

**Comment by RicardoSilvestr** [comment]
```
old x 1,462 ops/sec ±0.72% (93 runs sampled)
new x 930 ops/sec ±1.50% (86 runs sampled)
Fastest is old
```

**Comment by RicardoSilvestr** [comment]
```js
carc2.getIDCodeNoStereoTautomer = function getIDCodeNoStereoTautomer(mol, largestFragmentOnly){
  var e, genericTautomer;
  try {
    mol = mol.getCompactCopy_0();
    if (largestFragmentOnly) {
      mol.stripSmallFragments_0(true);
      (new carc2.MoleculeNeutralizer).neutralizeChargedMolecule(mol);
    }
    mol.stripStereoInformation_0();
    genericTautomer = (new carc2.TautomerHelper(mol)).createGenericTautomer();
    return (new carc2.Canonizer_0(genericTautomer, 8)).getIDCode_0();
  }
   catch ($e0) {
    $e0 = toJava($e0);
    if (instanceOf($e0, 20)) {
      e = $e0;
      (jl.$clinit_System() , jl.err).println('WARN: getIDCodeNoStereoTautomer() ' + e);
      return null;
    }
     else 
      throw toJs($e0);
  }
}
```
Most probably the problems is the function createGenericTautomer(), we should try to optimise it if possible

**Comment by RicardoSilvestr** [comment]
``` js
OCL.CanonizerUtil.TAUTOMER:
old x 1,403 ops/sec ±0.62% (93 runs sampled)
new x 1,407 ops/sec ±0.40% (96 runs sampled)
Fastest is new,old
```
```js
OCL.CanonizerUtil.NOSTEREO:
old x 1,345 ops/sec ±1.58% (92 runs sampled)
new x 1,668 ops/sec ±0.42% (95 runs sampled)
Fastest is new
```

**Comment by lpatiny** [comment]
But what is the speed of the old method to calculate the noStereoID ?

**Comment by RicardoSilvestr** [comment]
old method: 1,462 ops/sec ±0.72% (93 runs sampled)

**Comment by RicardoSilvestr** [comment]
Code:
[https://github.com/cheminfo/docker-pubchem/blob/a9f3b5c60aa42cdc3af8395b742e17f03d43b07b/pubchem/test/benchMarkNoStereoID.mjs#L1-L65](url)

Smiles Number: 4097 tautomer Smiles


**The time taken to execute the test once (secs):**
oldMethod: 5.8161008506
newMethodNoStereo: 5.4427260626
newMethodNoStereoTautomer: 41.257562766199996

**Test results: (each run generate the idCode for 4097 SMILES)**
oldMethod x 0.17 ops/sec ±0.46% (5 runs sampled)
newMethodNoStereo x 0.18 ops/sec ±0.32% (5 runs sampled)
newMethodNoStereoTautomer x 0.02 ops/sec ±2.54% (5 runs sampled)

**Comment by RicardoSilvestr** [comment]
The creation of ocl-cache collection was the only solution
