### ISSUE TITLE
How to handle parallel fetch during compound and substance importation?

### ISSUE THREAD

**Issue by RicardoSilvestr** [cheminfo/docker-pubchem#73]
The importation of compound collection using parallel fetch from ocl-cach resulted in DDOS, a solution needs to be find for future use.

**Comment by lpatiny** [comment]
Please give a link to the code that you need to limit. Is it in a loop or do you have the array before ?

**Comment by RicardoSilvestr** [comment]
The compounds loop of the sdf chunk:  
https://github.com/cheminfo/docker-pubchem/blob/27336d12a1b7b8d85d77b672511323cd8f538915/pubchem/src/plugins/compounds/sync/utils/importOneCompoundFile.js#L63-L128

Worker pool:
https://github.com/cheminfo/docker-pubchem/blob/27336d12a1b7b8d85d77b672511323cd8f538915/pubchem/src/plugins/compounds/sync/utils/improveCompoundPool.js#L11-L14

Compound parser:
https://github.com/cheminfo/docker-pubchem/blob/27336d12a1b7b8d85d77b672511323cd8f538915/pubchem/src/plugins/compounds/sync/utils/improveCompound.js#L10-L31

Fetch data from ocl-cache (getCompoundsData): 
https://github.com/cheminfo/docker-pubchem/blob/27336d12a1b7b8d85d77b672511323cd8f538915/pubchem/src/plugins/compounds/sync/utils/getCompoundsData.js#L27-L29

**Comment by RicardoSilvestr** [comment]
> Please give a link to the code that you need to limit. Is it in a loop or do you have the array before ?

In importOneCompoundFile we create an array "actions" containing the promises of fetching, once the loop is finished it resolve all promise, i think it's here we should limit the parallel process

**Comment by RicardoSilvestr** [comment]
Solution: 
we either limit the number of promises solved in parallel or we fetch a local version of ocl-cache by creating a bridge network between the two containers. The second option was the one chosen because the parallel importation is way faster.
